# Application Identity
spring.application.name=fix-iso20022-mapper-core

# Infrastructure - Netty Ingress
# Set to the port your FIX clients will connect to
app.tcp-port=9876

# Infrastructure - Kafka Egress
app.bootstrap-servers=localhost:9092
app.kafka-topic=iso20022.outbound.payloads

# Regional Market Configuration
# Options: USA, UK, SG
app.market=SG

# Mapping Rules: [FIX Tag]=[Template Name]
app.mapping-rules.exec=35=8=execution-report
app.mapping-rules.order=35=D=new-order-single

# Performance & Reliability
# Time to wait for Kafka before continuing (prevents pipeline stalls)
spring.kafka.producer.properties.max.block.ms=5000

# Observability
management.endpoints.web.exposure.include=prometheus,health,info
logging.level.com.byteentropy=INFO

# Give the app 5 seconds to finish sending messages before killing it
spring.kafka.producer.cleanup-timeout=5s